return {
    RarityWeights = {
        Common = 70, Uncommon = 20, Rare = 7, Epic = 2.5, Legendary = 0.45, Unknown = 0.2
    },
    RodConfig = {
        ["Owner Rod"] = {maxWeight = 10000, maxRarity = "Unknown"},
        ["Admin Rod"] = {maxWeight = 2000, maxRarity = "Unknown"},
        ["Developer Rod"] = {maxWeight = 1000, maxRarity = "Unknown"},
        ["Umbrella"] = {maxWeight = 650, maxRarity = "Unknown"},
        ["Katanaa"] = {maxWeight = 650, maxRarity = "Unknown"},
        ["Purple Saber"] = {maxWeight = 500, maxRarity = "Unknown"},
        ["Megalofriend"] = {maxWeight = 450, maxRarity = "Unknown"},
        ["Manifest"] = {maxWeight = 400, maxRarity = "Unknown"},
        ["Earthly"] = {maxWeight = 350, maxRarity = "Unknown"},
        ["Pirate Octopus"] = {maxWeight = 300, maxRarity = "Legendary"},
        ["LightingPunk Rod"] = {maxWeight = 280, maxRarity = "Legendary"},
        ["Frozen Rod"] = {maxWeight = 250, maxRarity = "Legendary"},
        ["GhostRod"] = {maxWeight = 250, maxRarity = "Legendary"},
        ["Fluorescent Rod"] = {maxWeight = 220, maxRarity = "Legendary"},
        ["Polarized"] = {maxWeight = 200, maxRarity = "Legendary"},
        ["Lightning"] = {maxWeight = 180, maxRarity = "Legendary"},
        ["Lucky Rod"] = {maxWeight = 150, maxRarity = "Epic"},
        ["Gold Rod"] = {maxWeight = 120, maxRarity = "Epic"},
        ["Angelic Rod"] = {maxWeight = 120, maxRarity = "Epic"},
        ["Basic Rod"] = {maxWeight = 100, maxRarity = "Epic"},
    },
    FishTable = {
        {name = "Boar Fish", rarity = "Common", minKg = 0.5, maxKg = 50},
        {name = "Blackcap Basslet", rarity = "Common", minKg = 0.5, maxKg = 45},
        {name = "Pumpkin Carved Shark", rarity = "Common", minKg = 1, maxKg = 60},
        {name = "Freshwater Piranha", rarity = "Common", minKg = 1, maxKg = 60},
        {name = "Hermit Crab", rarity = "Common", minKg = 0.8, maxKg = 40},
        {name = "Goliath Tiger", rarity = "Common", minKg = 2, maxKg = 70},
        {name = "Fangtooth", rarity = "Common", minKg = 1.5, maxKg = 55},
        {name = "Dead Spooky Koi Fish", rarity = "Uncommon", minKg = 5, maxKg = 80},
        {name = "Dead Scary Clownfish", rarity = "Uncommon", minKg = 4, maxKg = 75},
        {name = "Jellyfish", rarity = "Uncommon", minKg = 3, maxKg = 65},
        {name = "Lion Fish", rarity = "Rare", minKg = 10, maxKg = 120},
        {name = "Luminous Fish", rarity = "Rare", minKg = 12, maxKg = 130},
        {name = "Zombie Shark", rarity = "Rare", minKg = 20, maxKg = 150},
        {name = "Wraithfin Abyssal", rarity = "Rare", minKg = 15, maxKg = 140},
        {name = "Loving Shark", rarity = "Epic", minKg = 30, maxKg = 250},
        {name = "Monster Shark", rarity = "Epic", minKg = 35, maxKg = 280},
        {name = "Queen Crab", rarity = "Epic", minKg = 25, maxKg = 220},
        {name = "Pink Dolphin", rarity = "Epic", minKg = 40, maxKg = 300},
        {name = "Plasma Shark", rarity = "Legendary", minKg = 80, maxKg = 400},
        {name = "Ancient Relic Crocodile", rarity = "Unknown", minKg = 150, maxKg = 600},
        {name = "Ancient Whale", rarity = "Unknown", minKg = 200, maxKg = 800}
    }
}
